function(pybind11_stubgen target)
    cmake_parse_arguments(STUBGEN "" "PACKAGE;DESTINATION;COMPONENT" "" ${ARGN})
    if (NOT DEFINED STUBGEN_PACKAGE)
        set(STUBGEN_PACKAGE ${PY_BUILD_CMAKE_IMPORT_NAME})
    endif()
    if (NOT DEFINED STUBGEN_DESTINATION)
        set(STUBGEN_DESTINATION "")
    endif()
    if (NOT DEFINED STUBGEN_COMPONENT)
        set(STUBGEN_COMPONENT "python_stubs")
    endif()

    if (NOT DEFINED Python3_EXECUTABLE)
        find_package(Python3 REQUIRED COMPONENTS Interpreter)
    endif()

    # Create the stubgen command with generator expression inside the install block
    set(STUBGEN_MODULE "${STUBGEN_PACKAGE}.$<TARGET_FILE_BASE_NAME:${target}>")
    set(STUBGEN_CMD "${Python3_EXECUTABLE} -m pybind11_stubgen -o . --exit-code ${STUBGEN_MODULE}")
#    set(custom_script ${PROJECT_BINARY_DIR}/custom_install_scripts/install.cmake)
	set(custom_script cmake/install.cmake)
    configure_file(cmake/install.cmake.in ${custom_script} @ONLY)
    install(SCRIPT ${custom_script})
endfunction()
